package io.toro.ebay.model

public enum CharitySellerStatusCodeType {
	Closed,CreditCardAboutToExpire,CreditCardExpired,CustomCode,NotRegisteredLostDirectSellerStatus,Registered,RegisteredDirectSeller,RegisteredNoPaymentMethod,Suspended,TokenExpired;
}
