package io.toro.ebay.model

public enum IsoCurrencyCode {
	ANG,ATS,AUD,AWG,BBD,BEF,BGN,BMD,BND,BSD,CAD,CHF,CNY,COP,CRC,CZK,DEM,DKK,DOP,ESP,EUR,FIM,FRF,GBP,GRD,GTQ,HKD,HUF,IDR,IEP,ILS,INR,ITL,JMD,JPY,KRW,KYD,MVR,MYR,NLG,NOK,NZD,PEN,PHP,PLN,PTE,QAR,RON,RUR,SAR,SEK,SGD,THB,TRY,TTD,TWD,UAH,USD,UYU,VEF,VND,XCD,XPF,ZAR;
}
