package io.toro.ebay.model

public enum UPICaseStatusType {
	CLOSED,CLOSED_FVFCREDIT_NOSTRIKE,CLOSED_FVFCREDIT_STRIKE,CLOSED_NOFVFCREDIT_NOSTRIKE,CLOSED_NOFVFCREDIT_STRIKE,CS_CLOSED,EXPIRED,MY_PAYMENT_DUE,MY_RESPONSE_DUE,OTHER,OTHER_PARTY_RESPONSE_DUE;
}
